#!/bin/bash
# run: bash scripts/build-svg.bash > assets/icons.svg

icons=(
  "linkedin"
  "googlescholar"
  "orcid"
  "github"
  "bluesky"
  "python"
  "javascript"
  "oracle"
  "postgresql"
  "mysql"
  "sqlite"
  "mongodb"
  "keras"
  "pandas"
  "scikitlearn"
  "pypi"
  "pypi"
  "opencv"
  "d3dotjs"
  "processingfoundation"
  "opengl"
  "nodedotjs"
  "react"
  "flask"
  "docker"
  "podman"
  "githubactions"
  "gitlab"
  "proxmox"
  "vmware"
  "linux"
  "linux"
  "linuxcontainers"
  "jupyter"
  "nvidia"
  "paloaltonetworks"
  "hp"
  "pfsense"
  "opnsense"
  "openwrt"
  "wireguard"
  "openzfs"
  "netapp"
  "dell"
  "hp"
  "truenas"
  "ansible"
  "apacheguacamole"
  "debian"
  "redhat"
)

echo '<?xml version="1.0" encoding="utf-8"?><svg xmlns="http://www.w3.org/2000/svg"><defs>'
for item in "${icons[@]}"; do
  cat node_modules/simple-icons/icons/"$item".svg | sed "s/ xmlns=\"http\:\/\/www.w3.org\/2000\/svg\"//g" | sed "s/ role=\"img\"//g" | sed "s/svg/symbol/g" | sed "s/<symbol/<symbol id=\"$item\"/g"
done
echo '</defs></svg>'
